### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by wvicioso** [wvicioso/hackoverflow#37]

**Comment by LevytsRoman** [comment]
Do you want to deploy this as is or convert to rails?

**Comment by wvicioso** [comment]
I don't mind working with Sinatra so I say deploy it like this for now. I think its kind of fun fixing our old code. If you think we would be better off switching to rails early on I'm up for that too. If we do though I think the easiest way to do would be to just create a brand new repo.

**Comment by LevytsRoman** [comment]
[heroku-link](https://dbc-hackoverflow.herokuapp.com/questions)
